import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { DadosProvider } from '@/contexts/dados-context'
import { PdfProvider } from '@/contexts/pdf-context'
import { UserProvider } from '@/contexts/user-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <DadosProvider>
        <PdfProvider>
          <UserProvider>
            <body className={inter.className}>{children}</body>
          </UserProvider>
        </PdfProvider>
      </DadosProvider>
    </html>
  )
}
